name: next-monorepo-template_dev

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: next_monorepo_template_dev
      POSTGRES_PASSWORD: next_monorepo_template_dev
      POSTGRES_DB: next_monorepo_template_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U next_monorepo_template_dev"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
